SELECT MULTA_AP, NRO_TRAMITE, CONSECUTIVO, IDENTIFICADOR, CONSECUTIVO_AP
	  , ID_TIPO_DESC, VALOR_REAL, VALOR_DESCUENTO

FROM
(
	SELECT 'MULTA' AS MULTA_AP, DESCUENTO.NRO_TRAMITE, DESCUENTO.CONSECUTIVO, DESCUENTO.IDENTIFICADOR, 0 AS CONSECUTIVO_AP
	  , DESCUENTO.ID_TIPO_DESC, SUM(DESCUENTO.VALOR_REAL) AS VALOR_REAL, SUM(DESCUENTO.VALOR_DESCUENTO) AS VALOR_DESCUENTO
	FROM QUIPUX.COMP_DETALLE_DESCUENTO DESCUENTO
	  JOIN SOLICITUD_MAESTRO SM ON DESCUENTO.NRO_TRAMITE = SM.NRO_TRAMITE
	  JOIN COMP_TIPO_DESCUENTO TIPO ON TIPO.ID_TIPO_DESC = DESCUENTO.ID_TIPO_DESC
		AND ID_CONCEPTO = 2 AND CAPITAL_INTERES = 'I'
	WHERE
	  SM.FECHA_LIQUIDA BETWEEN TO_DATE(?,'YYYYMMDD HH24:MI:SS') AND TO_DATE(?,'YYYYMMDD HH24:MI:SS')
	  AND SM.ESTADO_RECIBO IN ('1', '2', '3')
	GROUP BY DESCUENTO.NRO_TRAMITE, DESCUENTO.CONSECUTIVO, DESCUENTO.IDENTIFICADOR
			, DESCUENTO.ID_TIPO_DESC
	UNION ALL

	SELECT DISTINCT 'AP' AS MULTA_AP, DESCUENTO.NRO_TRAMITE, DESCUENTO.CONSECUTIVO, DESCUENTO.IDENTIFICADOR, PAGO.CONSECUTIVO_AP
	  , DESCUENTO.ID_TIPO_DESC, DESCUENTO.VALOR_REAL, DESCUENTO.VALOR_DESCUENTO
	FROM QUIPUX.COMP_DETALLE_DESCUENTO DESCUENTO
	  JOIN SOLICITUD_MAESTRO SM ON DESCUENTO.NRO_TRAMITE = SM.NRO_TRAMITE
	  JOIN AP_PROCESO_AP_PAGO PAGO ON PAGO.NRO_TRAMITE = DESCUENTO.NRO_TRAMITE
	  JOIN COMP_TIPO_DESCUENTO TIPO ON TIPO.ID_TIPO_DESC = DESCUENTO.ID_TIPO_DESC
	  AND ID_CONCEPTO = 3 AND CAPITAL_INTERES = 'I'
	WHERE
	  SM.FECHA_LIQUIDA BETWEEN TO_DATE(?,'YYYYMMDD HH24:MI:SS') AND TO_DATE(?,'YYYYMMDD HH24:MI:SS')
	 AND SM.ESTADO_RECIBO IN ('1', '2', '3')
) AUX
