SELECT
	  (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
					FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones') AS ID_MES_CORTE
	,  ACT.CONSECUTIVO_MOROSO
	,  COALESCE(ACT.ID_USUARIO_MOROSO,'-1') AS ID_USUARIO_MOROSO
	,  COALESCE(ACT.NRO_COMPARENDO_MOROSO, '-1') AS NRO_COMPARENDO_MOROSO
	,  CAST(COALESCE(ACT.[FECHA_COMPARENDO],'1900-01-01') AS DATE)FECHA_COMPARENDO
	,  COALESCE(ACT.SK_FECHA_RESOLUCION,19000101) AS SK_FECHA
	,  FECHA_CALCULO_INTERES = (SELECT CONVERT(VARCHAR(8),fecha_fin,112) AS INT
								FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones')
	,  COALESCE(tipoComp.sk_Tipo_Comparendo, -1) AS Sk_Tipo_Comparendo
	,  COALESCE(Comp.sk_Estado_Comparendo, -1 ) AS sk_Estado_Comparendo
	--,  COALESCE(BNF.VALOR_REAL, ACT.VALOR_TARIFA) AS VALOR_TARIFA
	,	ACT.VALOR_TARIFA
	,  COALESCE(ACT.PROCESAR_INTERES,'NA')AS PROCESAR_INTERES
	,  26 AS Sk_Tipo
	,  COALESCE(P.sk_Persona, -1) AS sk_Persona
	,  COALESCE(V.sk_Vehiculo , -1) AS sk_Vehiculo
	,  COALESCE(STA.NUMERO_PLACA,'ND') AS NUMERO_PLACA
	FROM [STA_STTM].[dbo].STA_FACT_INTERESES_MOROSOS_PAGO_MES_ACTUAL ACT
	LEFT JOIN
		(
		SELECT Consecutivo_Moroso, sum(Valor_Intereses) as VALOR_INT
			FROM DWH_STTM..Fact_Cartera_Intereses_Moroso
			WHERE Id_Mes_Corte = (SELECT CASE WHEN (CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),5,2)  AS INTEGER)) -1 = 0
								THEN CAST( CAST( CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,4)  AS INTEGER) - 1 AS VARCHAR(4)) + '12' AS INTEGER)
								ELSE  CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,6)  AS INTEGER) -1	END AS ID_Mes_Corte
   								FROM dwh_sttm..Dim_Parametros WHERE id_Param = 'Cartera_Contravenciones')
				AND sk_tipo <> 22
			GROUP BY Consecutivo_Moroso
		) AUX  ON ACT.CONSECUTIVO_MOROSO = AUX.Consecutivo_Moroso
	--LEFT JOIN
	--	(SELECT DISTINCT CONSECUTIVO_MOROSO, VALOR_REAL, VALOR_DESCUENTO
	--		FROM STA_STTM..STA_FACT_INTERESES_MOROSOS_DESCUENTO_BNF WHERE MULTA_AP = 'MULTA'
	--	 ) BNF ON ACT.CONSECUTIVO_MOROSO = BNF.CONSECUTIVO_MOROSO
	LEFT JOIN STA_STTM.dbo.STA_FACT_INTERESES_CARTERA_MOROSOS STA ON STA.CONSECUTIVO_MOROSO = ACT.CONSECUTIVO_MOROSO
	LEFT JOIN DWH_STTM.dbo.Dim_Persona P ON P.Identificacion = ACT.ID_USUARIO_MOROSO
	LEFT JOIN DWH_STTM.dbo.Dim_Vehiculo V ON V.Placa = STA.NUMERO_PLACA
	LEFT JOIN DWH_STTM..Dim_Estado_Comparendo Comp
		ON CAST(ACT.ID_ESTADO_COMPARENDO AS NVARCHAR(2)) = Comp.Codigo_Estado_Comparendo
	LEFT JOIN DWH_STTM..Dim_Tipo_Comparendo tipoComp
		ON CAST(ACT.ID_TIPO_COMPARENDO AS NVARCHAR(2)) = tipoComp.Id_Tipo_Comparendo
	WHERE AUX.Consecutivo_Moroso IS NULL AND ACT.CONSECUTIVO_MOROSO IS NOT NULL
