SELECT
  AUX.ID_MES_CORTE
, AUX.CONSECUTIVO_MOROSO
, AUX.ID_USUARIO_MOROSO
, AUX.NRO_COMPARENDO_MOROSO
, AUX.FECHA_COMPARENDO
, AUX.SK_FECHA
, AUX.FECHA_CALCULO_INTERES
, AUX.Sk_Tipo_Comparendo
, AUX.sk_Estado_Comparendo
, SUM(AUX.VALOR_TARIFA) AS VALOR_TARIFA
, AUX.PROCESAR_INTERES
, AUX.Sk_Tipo
, AUX.sk_Persona
, AUX.sk_Vehiculo
FROM
(
	SELECT
	  (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
					FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones') AS ID_MES_CORTE
	,  COALESCE(ACT.CONSECUTIVO_MOROSO, -1) AS CONSECUTIVO_MOROSO
	,  COALESCE(ACT.ID_USUARIO_MOROSO,'-1') AS ID_USUARIO_MOROSO
	,  COALESCE(ACT.NRO_COMPARENDO_MOROSO, '-1') AS NRO_COMPARENDO_MOROSO
	,  CAST(COALESCE(ACT.[FECHA_COMPARENDO],'1900-01-01') AS DATE)FECHA_COMPARENDO
	,  COALESCE(ACT.SK_FECHA_RESOLUCION,19000101) AS SK_FECHA
	,  FECHA_CALCULO_INTERES = (SELECT CONVERT(VARCHAR(10),fecha_fin,120) AS INT
								FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones')
	,  COALESCE(ACT.ID_TIPO_COMPARENDO, -1) AS Sk_Tipo_Comparendo
	,  COALESCE(ACT.ID_ESTADO_COMPARENDO,-1) AS sk_Estado_Comparendo
	,  ACT.VALOR_TARIFA
	,  COALESCE(ACT.PROCESAR_INTERES,'NA')AS PROCESAR_INTERES
	,  28 AS Sk_Tipo
	,  COALESCE(P.sk_Persona, -1) AS sk_Persona
	,  COALESCE(V.sk_Vehiculo , -1) AS sk_Vehiculo
	FROM [STA_STTM].[dbo].STA_FACT_INTERESES_MOROSOS_PAGO_MES_ACTUAL ACT
	LEFT JOIN
		(
		SELECT Consecutivo_Moroso, sum(Valor_Intereses) as VALOR_INT
			FROM DWH_STTM..Fact_Cartera_Intereses_Moroso
			WHERE Id_Mes_Corte = (SELECT CASE WHEN (CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),5,2)  AS INTEGER)) -1 = 0
								THEN CAST( CAST( CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,4)  AS INTEGER) - 1 AS VARCHAR(4)) + '12' AS INTEGER)
								ELSE  CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,6)  AS INTEGER) -1	END AS ID_Mes_Corte
   								FROM dwh_sttm..Dim_Parametros WHERE id_Param = 'Cartera_Contravenciones')
			GROUP BY Consecutivo_Moroso
		) AUX  ON ACT.CONSECUTIVO_MOROSO = AUX.Consecutivo_Moroso
	LEFT JOIN STA_STTM.dbo.STA_FACT_INTERESES_CARTERA_MOROSOS STA ON STA.CONSECUTIVO_MOROSO = ACT.CONSECUTIVO_MOROSO
	LEFT JOIN DWH_STTM.dbo.Dim_Persona P ON P.Identificacion = ACT.ID_USUARIO_MOROSO
	LEFT JOIN DWH_STTM.dbo.Dim_Vehiculo V ON V.Placa = STA.NUMERO_PLACA
	WHERE AUX.Consecutivo_Moroso IS NULL AND ACT.CONSECUTIVO_MOROSO IS  NULL
) AUX
GROUP BY
  AUX.ID_MES_CORTE
, AUX.CONSECUTIVO_MOROSO
, AUX.ID_USUARIO_MOROSO
, AUX.NRO_COMPARENDO_MOROSO
, AUX.FECHA_COMPARENDO
, AUX.SK_FECHA
, AUX.FECHA_CALCULO_INTERES
, AUX.Sk_Tipo_Comparendo
, AUX.sk_Estado_Comparendo
, AUX.PROCESAR_INTERES
, AUX.Sk_Tipo
, AUX.sk_Persona
, AUX.sk_Vehiculo
