-- Archivo SQL generado automáticamente
SELECT
        M.CONSECUTIVO_MOROSO
      , M.ID_USUARIO_MOROSO
      , M.NRO_COMPARENDO_MOROSO
      , M.TIPO_COMPARENDO
      , M.NUMERO_RES
      , M.FECHA_RESOLUCION
      , M.TIPO_SANCION_MOROSO
      , M.VALOR_MULTA
      , M.ESTADO_MOROSO
      , FECHA_COMPARENDO
      , M.COBRO_COACTIVO
      , M.FECHA_COBRO_COACTIVO
      , M.DESCRIPCION_ESTADO
      , M.NUMERO_PLACA
      , M.DESC_CLASE
      , M.DESC_SERVI
      , M.DESCRIPCION_COMPARENDO
      , M.NOMBRES
      , M.APELLIDOS
      , M.TELEFONO
      , M.DIRECCION
      , M.VALOR_INTERESES_MOROSOS
      , 'MULTA' AS PROCESAR_INTERES
      ,  (SELECT CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,6)  AS INTEGER) AS ID_Mes_Corte
                           	   FROM dwh_sttm..Dim_Parametros WHERE id_Param = 'Cartera_Contravenciones') AS Id_Mes_Corte
FROM STA_Fact_Cartera_Moroso M
	WHERE M.PROCESAR_INTERES = 1 AND TIPO_SANCION_MOROSO <> 'A'
     AND M.VIGENTE = 'S'
UNION ALL

--- REACTIVACION Y GENERADOS
  SELECT
        M.CONSECUTIVO_MOROSO
      , M.ID_USUARIO_MOROSO
      , M.NRO_COMPARENDO_MOROSO
      , M.TIPO_COMPARENDO
      , M.NUMERO_RES
      , M.FECHA_RESOLUCION
      , M.TIPO_SANCION_MOROSO
      , M.VALOR_MULTA
      , M.ESTADO_MOROSO
      , M.FECHA_COMPARENDO
      , M.COBRO_COACTIVO
      , M.FECHA_COBRO_COACTIVO
      , M.DESCRIPCION_ESTADO
      , M.NUMERO_PLACA
      , M.DESC_CLASE
      , NULL as DESC_SERVI
      , M.DESCRIPCION_COMPARENDO
      , M.NOMBRES
      , M.APELLIDOS
      , M.TELEFONO
      , M.DIRECCION
      , M.VALOR_INTERESES_MOROSOS
      , 'MULTA N' AS PROCESAR_INTERES
      ,  (SELECT CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,6)  AS INTEGER) AS ID_Mes_Corte
                           	   FROM dwh_sttm..Dim_Parametros WHERE id_Param = 'Cartera_Contravenciones') AS Id_Mes_Corte
FROM STA_STTM.dbo.STA_Fact_Cartera_Generada_Mes M
WHERE M.TIPO_SANCION_MOROSO <> 'A' AND M.ID_CLASE_ORIGEN in (3,4)
UNION ALL

SELECT
        M.CONSECUTIVO_MOROSO
      , M.ID_USUARIO_MOROSO
      , M.NRO_COMPARENDO_MOROSO
      , M.TIPO_COMPARENDO
      , M.NUMERO_RES
      , M.FECHA_RESOLUCION
      , M.TIPO_SANCION_MOROSO
      , M.VALOR_MULTA
      , M.ESTADO_MOROSO
      , FECHA_COMPARENDO
      , M.COBRO_COACTIVO
      , M.FECHA_COBRO_COACTIVO
      , M.DESCRIPCION_ESTADO
      , M.NUMERO_PLACA
      , M.DESC_CLASE
      , M.DESC_SERVI
      , M.DESCRIPCION_COMPARENDO
      , M.NOMBRES
      , M.APELLIDOS
      , M.TELEFONO
      , M.DIRECCION
      , M.VALOR_INTERESES_MOROSOS
      , 'AP' AS PROCESAR_INTERES
      , (SELECT CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,6)  AS INTEGER) AS ID_Mes_Corte
                           	   FROM dwh_sttm..Dim_Parametros WHERE id_Param = 'Cartera_Contravenciones') AS Id_Mes_Corte
FROM STA_Fact_Cartera_Moroso M
	WHERE TIPO_SANCION_MOROSO = 'A'
	AND M.VIGENTE = 'S'
group by
M.CONSECUTIVO_MOROSO
      , M.ID_USUARIO_MOROSO
      , M.NRO_COMPARENDO_MOROSO
      , M.TIPO_COMPARENDO
      , M.NUMERO_RES
      , M.FECHA_RESOLUCION
      , M.TIPO_SANCION_MOROSO
      , M.VALOR_MULTA
      , M.ESTADO_MOROSO
      , FECHA_COMPARENDO
      , M.COBRO_COACTIVO
      , M.FECHA_COBRO_COACTIVO
      , M.DESCRIPCION_ESTADO
      , M.NUMERO_PLACA
      , M.DESC_CLASE
      , M.DESC_SERVI
      , M.DESCRIPCION_COMPARENDO
      , M.NOMBRES
      , M.APELLIDOS
      , M.TELEFONO
      , M.DIRECCION
      , M.VALOR_INTERESES_MOROSOS
