SELECT
	 MAX(AUX2.ID_MES_CORTE) AS ID_MES_CORTE
	,AUX2.CONSECUTIVO_MOROSO
	,MAX(AUX2.ID_USUARIO_MOROSO) AS ID_USUARIO_MOROSO
	,MAX(AUX2.NRO_COMPARENDO_MOROSO) AS NRO_COMPARENDO_MOROSO
	,MAX(AUX2.FECHA_COMPARENDO) AS FECHA_COMPARENDO
	,MAX(AUX2.SK_FECHA)AS  SK_FECHA
	,MAX(COALESCE(AUX2.FECHA_CALCULO_INTERES,'1900-01-01')) AS FECHA_CALCULO_INTERES
	,MAX(COALESCE(tipoComp.Sk_Tipo_Comparendo, -1)) AS Sk_Tipo_Comparendo
	,MAX(COALESCE(Comp.sk_Estado_Comparendo, -1)) AS sk_Estado_Comparendo
	,SUM(AUX2.VALOR_TARIFA - AUX2.VALOR_TARIFA2) as VALOR_INTERESES
	,MAX(AUX2.PROCESAR_INTERES) AS PROCESAR_INTERES
	,27 AS Sk_Tipo
	,MAX(AUX2.sk_Persona) AS sk_Persona
	,MAX(COALESCE(AUX2.sk_Vehiculo,-1)) AS sk_Vehiculo
	,MAX(AUX2.NUMERO_PLACA) AS NUMERO_PLACA

FROM
(
	SELECT
			 AUX.ID_MES_CORTE,
			 AUX.CONSECUTIVO_MOROSO,AUX.ID_USUARIO_MOROSO,AUX.NRO_COMPARENDO_MOROSO,AUX.FECHA_COMPARENDO
			,AUX.SK_FECHA,AUX.FECHA_CALCULO_INTERES,AUX.Id_Tipo_Comparendo,AUX.Id_Estado_Comparendo
			,COALESCE(BNF.VALOR_REAL, AUX.VALOR_TARIFA) AS VALOR_TARIFA
			,AUX.VALOR_TARIFA2 ,AUX.PROCESAR_INTERES,AUX.Sk_Tipo,AUX.sk_Persona,AUX.sk_Vehiculo,AUX.NUMERO_PLACA
	FROM
	(
			SELECT
			    (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
							FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones') AS ID_MES_CORTE
				,  ACT.CONSECUTIVO_MOROSO
				,  COALESCE(ACT.ID_USUARIO_MOROSO,'-1') AS ID_USUARIO_MOROSO
				,  COALESCE(ACT.NRO_COMPARENDO_MOROSO, '-1') AS NRO_COMPARENDO_MOROSO
				,  CAST(COALESCE(ACT.[FECHA_COMPARENDO],'1900-01-01') AS DATE)FECHA_COMPARENDO
				,  COALESCE(ACT.SK_FECHA_RESOLUCION,19000101) AS SK_FECHA
				,  FECHA_CALCULO_INTERES = (SELECT CONVERT(VARCHAR(8),fecha_fin,112) AS INT
											FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones')
			    ,  COALESCE(ACT.ID_TIPO_COMPARENDO, -1) AS Id_Tipo_Comparendo
				,  COALESCE(ACT.ID_ESTADO_COMPARENDO,-1) AS Id_Estado_Comparendo
				,  SUM(ACT.VALOR_TARIFA) AS VALOR_TARIFA
				,  0 AS VALOR_TARIFA2
				,  COALESCE(ACT.PROCESAR_INTERES,'NA')AS PROCESAR_INTERES
				,  27 AS Sk_Tipo
				,  COALESCE(P.sk_Persona, -1) AS sk_Persona
				,   -1 AS sk_Vehiculo
				,  AUX.Consecutivo_Moroso AS Consecutivo_Moroso2
				,  'ND' AS NUMERO_PLACA
			FROM
				[STA_STTM].[dbo].STA_FACT_INTERESES_MOROSOS_PAGO_MES_ACTUAL ACT
				JOIN
				(
					SELECT  AUX.Consecutivo_Moroso
						FROM
						(
							SELECT Consecutivo_Moroso
							FROM DWH_STTM..Fact_Cartera_Moroso
							WHERE Id_Mes_Corte = (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
													FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones')
							AND Sk_Tipo IN (4,6)
						) AUX
						INNER JOIN
						(
							SELECT Consecutivo_Moroso
							FROM DWH_STTM..Fact_Cartera_Intereses_Moroso
							WHERE Id_Mes_Corte = (SELECT CASE WHEN (CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),5,2)  AS INTEGER)) -1 = 0
												THEN CAST( CAST( CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,4)  AS INTEGER) - 1 AS VARCHAR(4)) + '12' AS INTEGER)
												ELSE  CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,6)  AS INTEGER) -1	END AS ID_Mes_Corte
												FROM dwh_sttm..Dim_Parametros WHERE id_Param = 'Cartera_Contravenciones')
								AND sk_tipo <> 22
						)AUX1 ON AUX.Consecutivo_Moroso = AUX1.Consecutivo_Moroso
				) AUX
					ON ACT.CONSECUTIVO_MOROSO = AUX.Consecutivo_Moroso
				LEFT JOIN DWH_STTM.dbo.Dim_Persona P ON P.Identificacion = ACT.ID_USUARIO_MOROSO
			GROUP BY ACT.CONSECUTIVO_MOROSO
				,  COALESCE(ACT.ID_USUARIO_MOROSO,'-1')
				,  COALESCE(ACT.NRO_COMPARENDO_MOROSO, '-1')
				,  CAST(COALESCE(ACT.[FECHA_COMPARENDO],'1900-01-01') AS DATE)
				,  COALESCE(ACT.SK_FECHA_RESOLUCION,19000101)
			    ,  COALESCE(ACT.Id_TIPO_COMPARENDO, -1)
				,  COALESCE(ACT.Id_ESTADO_COMPARENDO,-1)
				,  COALESCE(ACT.PROCESAR_INTERES,'NA')
				,  COALESCE(P.sk_Persona, -1)
				,  AUX.Consecutivo_Moroso

	)AUX
		LEFT JOIN ( SELECT DISTINCT CONSECUTIVO_MOROSO, VALOR_REAL, VALOR_DESCUENTO
					 FROM STA_STTM..STA_FACT_INTERESES_MOROSOS_DESCUENTO_BNF
				  ) BNF
				ON AUX.CONSECUTIVO_MOROSO = BNF.CONSECUTIVO_MOROSO

UNION ALL

	--OK 27 PART1
	SELECT
	  (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
							FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones') AS ID_MES_CORTE
	   ,FAI.Consecutivo_Moroso,FAI.ID_USUARIO_MOROSO,FAI.NRO_COMPARENDO_MOROSO,FAI.FECHA_COMPARENDO
	   ,FAI.SK_FECHA,'1900-01-01' AS FECHA_CALCULO_INTERES,FAI.sk_Tipo_Comparendo,FAI.sk_Estado_Comparendo,0 AS VALOR_TARIFA
	   ,sum(Valor_Intereses_Morosos) as VALOR_TARIFA2,FAI.PROCESAR_INTERES,FAI.Sk_Tipo,FAI.sk_Persona,FAI.sk_Vehiculo,FAI.Numero_Placa
		FROM DWH_STTM..Fact_Cartera_Moroso FAI
		INNER JOIN (
						SELECT Consecutivo_Moroso
						FROM DWH_STTM..Fact_Cartera_Moroso
						WHERE Id_Mes_Corte = (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
												FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones')
						AND Sk_Tipo IN (4,6)
					) AUX
				ON FAI.Consecutivo_Moroso = AUX.Consecutivo_Moroso
				AND  Id_Mes_Corte = (SELECT CASE WHEN (CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),5,2)  AS INTEGER)) -1 = 0
									THEN CAST( CAST( CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,4)  AS INTEGER) - 1 AS VARCHAR(4)) + '12' AS INTEGER)
									ELSE  CAST(SUBSTRING(CONVERT(VARCHAR(8),Fecha_Inicio,112),1,6)  AS INTEGER) -1	END AS ID_Mes_Corte
									FROM dwh_sttm..Dim_Parametros WHERE id_Param = 'Cartera_Contravenciones')
				AND FAI.sk_tipo IN (1,12)

	GROUP BY FAI.ID_MES_CORTE,FAI.Consecutivo_Moroso,FAI.ID_USUARIO_MOROSO,FAI.NRO_COMPARENDO_MOROSO,FAI.FECHA_COMPARENDO
	   ,FAI.Sk_Fecha, FAI.Sk_Tipo_Comparendo,FAI.sk_Estado_Comparendo
	   ,FAI.PROCESAR_INTERES,FAI.Sk_Tipo,FAI.sk_Persona,FAI.sk_Vehiculo,FAI.Numero_Placa
) AUX2
 LEFT JOIN DWH_STTM..Dim_Estado_Comparendo Comp
	ON CAST(AUX2.ID_ESTADO_COMPARENDO AS NVARCHAR(5)) = Comp.Codigo_Estado_Comparendo
 LEFT JOIN DWH_STTM..Dim_Tipo_Comparendo tipoComp
	ON CAST(AUX2.ID_TIPO_COMPARENDO AS NVARCHAR(5)) = tipoComp.Id_Tipo_Comparendo
GROUP BY AUX2.CONSECUTIVO_MOROSO
