SELECT (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
         FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones') AS Id_Mes_Corte,
        -1 AS CONSECUTIVO_MOROSO,
        -1 AS ID_USUARIO,
        'N/A' AS NRO_COMPARENDO,
        -1 AS SK_TIPO_COMPARENDO,
        -1 AS SK_ESTADO_COMPARENDO,
        19000101 AS SK_FECHA,
        '1900-01-01' AS FECHA_CALCULO_INTERESES,
        SUM(VALOR_TARIFA) AS VALOR_INTERESES,
        0 AS VALOR_TARIFA,
        0 AS DIFERENCIA,
        -1 PROCESAR_INTERES,
        30 AS SK_TIPO,
        -1 AS SK_TIPO_INTERES,
        -1 AS SK_PERSONA,
        -1 AS SK_VEHICULO
FROM [STA_STTM].[dbo].STA_FACT_INTERESES_MOROSOS_PAGO_MES_ACTUAL
