SELECT
  (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
				FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones') AS ID_MES_CORTE
,  MA.Consecutivo_Moroso
,  COALESCE(STA.ID_USUARIO_MOROSO,'-1') AS ID_USUARIO_MOROSO
,  STA.NRO_COMPARENDO_MOROSO
,  CAST(STA.[FECHA_COMPARENDO] AS DATE)FECHA_COMPARENDO
,  CAST(CONVERT(VARCHAR(8),STA.[FECHA_RESOLUCION],112)AS INT )AS Sk_Fecha
,  FECHA_CALCULO_INTERES = (SELECT CONVERT(VARCHAR(8),fecha_fin,112) AS INT
							FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones')
,  COALESCE(TC.Sk_Tipo_Comparendo, -1) AS Sk_Tipo_Comparendo
,  COALESCE(EC.sk_Estado_Comparendo,-1) AS sk_Estado_Comparendo
,  MA.VALOR_INTERESES_ACTUAL
,  MA.VALOR_INTERESES_ANTERIOR
,  MA.DIFERENCIA
,  COALESCE(STA.NUMERO_PLACA,'ND') AS NUMERO_PLACA
,  MA.Procesar_Interes
,  25 AS Sk_Tipo
,  P.sk_Persona
,  V.sk_Vehiculo
FROM STA_STTM.dbo.STA_FACT_INTERESES_MOROSOS_MES_ACTUAL MA
  LEFT JOIN STA_STTM.dbo.STA_FACT_INTERESES_CARTERA_MOROSOS STA ON STA.CONSECUTIVO_MOROSO = MA.CONSECUTIVO_MOROSO
  LEFT JOIN DWH_STTM.dbo.Dim_Tipo_Comparendo TC ON STA.TIPO_COMPARENDO = TC.Id_Tipo_Comparendo
  LEFT JOIN DWH_STTM.dbo.Dim_Estado_Comparendo EC ON STA.ESTADO_MOROSO = EC.Codigo_Estado_Comparendo
  LEFT JOIN DWH_STTM.dbo.Dim_Persona P ON P.Identificacion = STA.ID_USUARIO_MOROSO
  LEFT JOIN DWH_STTM.dbo.Dim_Vehiculo V ON V.Placa = STA.NUMERO_PLACA
