SELECT
  SM.NRO_TRAMITE,
  SM.FECHA_LIQUIDA,
  SI.ID_TARIFA,
  TT.DESC_CONCEPTO,
  SI.VALOR_TARIFA,
  --CASE WHEN length(TRANSLATE(SI.IDENTIFICADOR,'0123456789',' ')) > 10 THEN NULL ELSE SI.IDENTIFICADOR END AS IDENTIFICADOR,
  CASE WHEN length(SI.IDENTIFICADOR) > 10 THEN NULL ELSE SI.IDENTIFICADOR END AS IDENTIFICADOR,
  MOR.ID_USUARIO_MOROSO,
  CAST( TO_CHAR(MOR.FECHA_RESOLUCION, 'YYYYMMDD') AS INTEGER) AS FECHA_RESOLUCION,
  MOR.NRO_COMPARENDO_MOROSO,
  MOR.ESTADO_MOROSO,
  COMP.FECHA,
  COMP.TIPO_COMPARENDO,
  COMP.NUMERO_PLACA
FROM SOLICITUD_MAESTRO SM
left JOIN SOLICITUD_INGRESO SI ON SM.NRO_TRAMITE = SI.NRO_TRAMITE
LEFT JOIN MOROSOS MOR ON CASE WHEN length(TRANSLATE(SI.IDENTIFICADOR,'0123456789',' ')) > 10 THEN NULL ELSE SI.IDENTIFICADOR END = TO_CHAR(MOR.CONSECUTIVO_MOROSOS)
LEFT JOIN COMPARENDOS COMP ON MOR.NRO_COMPARENDO_MOROSO = COMP.NRO_COMPARENDO
left JOIN TIPO_TARIFAS TT ON SI.ID_TARIFA = TT.ID_TARIFA
WHERE
	SM.FECHA_LIQUIDA Between TO_DATE(?,'YYYYMMDD HH24:MI:SS') AND TO_DATE(?,'YYYYMMDD HH24:MI:SS')
	AND SI.ID_TARIFA IN (361, 364, 369, 371, 374, 375, 383, 385, 384, 386, 387, 388, 394, 395, 396, 397, 402, 404, 408, 409, 411, 412, 414, 416, 418, 420, 421, 422, 449)
  	AND SM.ESTADO_RECIBO IN ('1', '2', '3')
order by 1
