SELECT
Id_Mes_Corte, NRO_TRAMITE, CONSECUTIVO_AP, NRO_COMPARENDO_MOROSO, SK_FECHA_RESOLUCION, FECHA_COMPARENDO, sk_Tipo_Comparendo, sk_Estado_Comparendo, ID_USUARIO_MOROSO, PROCESAR_INTERES, FECHA_LIQUIDA, Sk_Tipo_Cartera, Valor_Tarifa, Valor_Intereses, Valor_Bnt_diff_Amnistia, Valor_Bnt_Amnistia, Valor_Bnt_Beneficio, bnt_ok
FROM
(
--morosos tarifas de amnistia AP
SELECT (SELECT CAST(CONVERT(VARCHAR(6),fecha_fin,112) AS INT )
		FROM DWH_STTM..Dim_Parametros WHERE Id_param = 'Cartera_Contravenciones') AS Id_Mes_Corte
	  ,PAGO.NRO_TRAMITE
	  ,BNF.CONSECUTIVO_AP
	  ,PAGO.NRO_COMPARENDO_MOROSO
	  ,PAGO.SK_FECHA_RESOLUCION
	  ,PAGO.FECHA_COMPARENDO
	  ,PAGO.sk_Tipo_Comparendo
	  ,PAGO.sk_Estado_Comparendo
	  ,PAGO.ID_USUARIO_MOROSO
	  ,'AP:408,409,411,412' AS PROCESAR_INTERES
	  ,PAGO.FECHA_LIQUIDA
	  , 53 AS Sk_Tipo_Cartera
      ,row_number() OVER (PARTITION BY BNF.CONSECUTIVO_AP order by PAGO.NRO_TRAMITE DESC) AS orden
	  ,SUM(PAGO.VALOR_TARIFA) AS Valor_Tarifa
	  ,SUM(BNF.VALOR_REAL - PAGO.VALOR_TARIFA) AS Valor_Intereses
	  ,SUM(PAGO.VALOR_TARIFA - BNF.VALOR_DESCUENTO)AS Valor_Bnt_diff_Amnistia
	  ,SUM(BNF.VALOR_DESCUENTO) AS Valor_Bnt_Amnistia
	  ,SUM(BNF.VALOR_REAL - BNF.VALOR_DESCUENTO) AS Valor_Bnt_Beneficio
	  ,CASE WHEN (PAGO.VALOR_TARIFA / COALESCE(BNF.VALOR_REAL,1)) BETWEEN 0.28 AND 0.32
			THEN 'SI' ELSE 'NO' END AS bnt_ok
FROM (
		SELECT NRO_TRAMITE
			  ,COALESCE(NRO_COMPARENDO_MOROSO, '0') AS NRO_COMPARENDO_MOROSO
			  ,SK_FECHA_RESOLUCION
			  ,FECHA_COMPARENDO
			  ,COALESCE(tipoComp.sk_Tipo_Comparendo, -1) AS sk_Tipo_Comparendo
			  ,COALESCE(Comp.sk_Estado_Comparendo, -1 ) AS sk_Estado_Comparendo
			  ,COALESCE(ID_USUARIO_MOROSO, '-1') AS ID_USUARIO_MOROSO
			  ,PROCESAR_INTERES
			  ,FECHA_LIQUIDA
			  ,SUM(VALOR_TARIFA) AS VALOR_TARIFA
		FROM STA_STTM..STA_FACT_INTERESES_MOROSOS_PAGO_MES_ACTUAL PAGO
			LEFT JOIN DWH_STTM..Dim_Estado_Comparendo Comp
				ON CAST(PAGO.ID_ESTADO_COMPARENDO AS NVARCHAR(2)) = Comp.Codigo_Estado_Comparendo
			LEFT JOIN DWH_STTM..Dim_Tipo_Comparendo tipoComp
				ON CAST(PAGO.ID_TIPO_COMPARENDO AS NVARCHAR(2)) = tipoComp.Id_Tipo_Comparendo
		WHERE  PAGO.ID_TARIFA IN (408, 409, 411, 412) and PAGO.NRO_TRAMITE not in ('29934074') --tarifas de morosos con amnistia
		GROUP BY NRO_TRAMITE
			  ,COALESCE(NRO_COMPARENDO_MOROSO, '0')
			  ,SK_FECHA_RESOLUCION
			  ,FECHA_COMPARENDO
			  ,COALESCE(tipoComp.sk_Tipo_Comparendo, -1)
			  ,COALESCE(Comp.sk_Estado_Comparendo, -1)
			  ,COALESCE(ID_USUARIO_MOROSO, '-1')
			  ,PROCESAR_INTERES
			  ,FECHA_LIQUIDA
	) PAGO
	JOIN (SELECT NRO_TRAMITE, CONSECUTIVO_AP, SUM(VALOR_REAL) AS VALOR_REAL, SUM(VALOR_DESCUENTO) AS VALOR_DESCUENTO
			FROM STA_STTM..STA_FACT_INTERESES_MOROSOS_DESCUENTO_BNF WHERE MULTA_AP = 'AP'
			GROUP BY NRO_TRAMITE, CONSECUTIVO_AP
		 ) BNF
		ON PAGO.NRO_TRAMITE = BNF.NRO_TRAMITE
WHERE BNF.CONSECUTIVO_AP NOT IN (357233,358969,359113,359496,361631,361815,367259)
GROUP BY PAGO.NRO_TRAMITE
	  ,BNF.CONSECUTIVO_AP
	  ,PAGO.NRO_COMPARENDO_MOROSO
	  ,PAGO.SK_FECHA_RESOLUCION
	  ,PAGO.FECHA_COMPARENDO
	  ,PAGO.sk_Tipo_Comparendo
	  ,PAGO.sk_Estado_Comparendo
	  ,PAGO.ID_USUARIO_MOROSO
	  ,PAGO.PROCESAR_INTERES
	  ,PAGO.FECHA_LIQUIDA
	  ,CASE WHEN (PAGO.VALOR_TARIFA / COALESCE(BNF.VALOR_REAL,1)) BETWEEN 0.28 AND 0.32
			THEN 'SI' ELSE 'NO' END
) SQ
WHERE orden = 1
